services:
  mongodb8:
    image: mongo:8.0.1
    container_name: mongodb8
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata8:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yu7i
      - MONGO_INITDB_ROOT_PASSWORD=53cret
      - MONGO_INITDB_DATABASE=employee
    networks:
      - mongo

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=yu7i
      - ME_CONFIG_BASICAUTH_PASSWORD=53cret
    volumes:
      - ./mongo-express:/data/db
    ports:
      - "8002:8081"
    networks:
      - mongo
    depends_on:
      - mongodb8
volumes:
  dbdata8:
networks:
  mongo: # docker-compose-files_mongo
    driver: bridge
