spring:
  application.name: spring-boot-mongodb-migration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: employee
      username: yu7i
      password: 53cret
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080

####### Mongock Properties ###########
mongock:
  migration-scan-package:
    - id.my.hendisantika.mongodbmigration.config.dbmigrations

logging:
  level:
    org.springframework: error
    org.springframework.security: debug

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-doc
